### PR TITLE
(fix) Update form fetch request to return the latest form by uuid or name

### PR DESCRIPTION
**Pull request by CynthiaKamau**
## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary

When fetching a form by name, the current form engine returns a list of forms with that name, including retired forms. Using the o3 forms endpoint, it is possible that the returned result might be a retired form. This PR ensures that the latest (most recent) form is fetched instead of the first item in the array, which could be a retired form.

### CODE REVIEW

**Review by arodidev — APPROVED** [review]
Thanks @CynthiaKamau

**Comment by samuelmale** [comment]
> Using the o3 forms endpoint, it is possible that the returned result might be a retired form.

Can you also switch to using the o3 endpoint? Currently, we are [using the standard "form" resource endpoint](https://github.com/openmrs/openmrs-form-engine-lib/blob/1820076ed77fbbfdd6dce39f83fd87e1f446874f/src/api/api.ts#L100-L102). It maybe worth checking if it supports a filter for excluding retired resources.

**Comment by CynthiaKamau** [comment]
> > Using the o3 forms endpoint, it is possible that the returned result might be a retired form.
> 
> Can you also switch to using the o3 endpoint? Currently, we are [using the standard "form" resource endpoint](https://github.com/openmrs/openmrs-form-engine-lib/blob/1820076ed77fbbfdd6dce39f83fd87e1f446874f/src/api/api.ts#L100-L102). It maybe worth checking if it supports a filter for excluding retired resources.

The response from the o3 endpoint is not the latest form if you fetch a form by a name, you can try test as well

**Comment by samuelmale** [comment]
@CynthiaKamau by latest you meaning in terms of the published form version?

**Comment by samuelmale** [comment]
@CynthiaKamau hhmm!! Maybe this is happening for snapshot versions (unpublished versions)? @ibacher are you aware of this?

**Comment by CynthiaKamau** [comment]
> @CynthiaKamau hhmm!! Maybe this is happening for snapshot versions (unpublished versions)? @ibacher are you aware of this?

Does dev3 run on a snapshot version? 
Screenshot 2024-07-05 at 10 53 59

**Comment by samuelmale** [comment]
@CynthiaKamau by "snapshot" I was referring to form versions not the module

**Comment by ibacher** [comment]
> The response from the o3 endpoint is not the latest form if you fetch a form by a name, you can try test as well

I would recommend passing form UUIDs rather than form names to the O3 Forms service...

**Comment by samuelmale** [comment]
@ibacher I think some folks find it convenient to manage configs using the form names assuming the modelling supports that (as secondary identifiers). The standard form REST API seems to work correctly unlike the o3 endpoint as flagged by @CynthiaKamau. Is it worth investigating why?

**Comment by ibacher** [comment]
>  think some folks find it convenient to manage configs using the form names assuming the modelling supports that 

Right... I'm just saying maybe don't naively pass it to the o3forms until that bug is fixed. A call to the `forms` endpoint to get the UUID doesn't seem that bad...

**Comment by samuelmale** [comment]
Sweet! I just wanted to confirm that you're aware of the bug and maybe at a later point we will move to using the o3 endpoint. It's inevitable in my pov!

**Review by samuelmale — APPROVED** [review]
I don't seem to wrap my head around how using a dynamic index fixes the issue, but I'll give this a pass.

**Comment by ibacher** [comment]
Yeah, it would be better, I think, to use the first non-retired one. Relying on the order like this is not guaranteed to work, though it will in the common case.

**Pull request merged**
