### PR TITLE
Updating License from MIT to MPL v2 w HCD, without Copyright

### PR DESCRIPTION
**Pull request by gracepotma**
This React Form Engine, now called the "OpenMRS Form Engine", previously-called the OHRI Form Engine, had an MIT license and UCSF (c). Today, with support from UCSF team members, we have worked together (OMRS and UCSF) to move the source repo into the OpenMRS community. I would like to follow our conventions and change this to MPL v2 with Healthcare Disclaimer to follow community conventions so this can be safely re-used and co-maintained by our global OpenMRS community.

### CODE REVIEW

**Review by samuelmale — APPROVED** [review]
Thanks Grace!

**Comment by ebambo** [comment]
@gracepotma agreed and thanks for catching that. Do you think we should apply this to all our repos since at the end they are all supposed to be used by the wider community?

**Comment by gracepotma** [comment]
That would actually be very perfect @ebambo !!

**Comment by MwaririM** [comment]
@gracepotma Thank you for this.

**Pull request merged**
