### PR TITLE
(feat) O3-2212: hide the form navigation menu for single page forms

### PR DESCRIPTION
**Pull request by jona42-ui**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [x] My work includes tests or is validated by existing tests.

## Summary

Add ability to hide form navigation if the form has only one page

## Related Issue

https://issues.openmrs.org/browse/O3-2212

### CODE REVIEW

**Comment by jona42-ui** [comment]
sure thanks @gracepotma

**Comment by gracepotma** [comment]
@jona42-ui I still don't see a screenshot, am I missing something maybe?

**Comment by jona42-ui** [comment]
@gracepotma server is not running well
Screenshot from 2023-06-28 07-21-35

**Comment by denniskigen** [comment]
You should be able to run the server. What approach are you using?

**Comment by jona42-ui** [comment]
After linking the built form engine to the form app in the patient chart app, then running 
`yarn start --port 3000 --sources packages/esm-form-engine-app`;
It seemingly loads the spa app and ends in a white screen;
Screenshot from 2023-06-29 14-14-36

**Comment by jona42-ui** [comment]
Screenshot from 2023-06-29 14-19-35

**Comment by samuelmale** [comment]
@jona42-ui you can link the form engine locally within the form builder app by running:

```
 yarn link ${path-to-form-engine-root-dir-on-your-machine}
```

Eg. 

```
yarn link /Users/sam/openmrs-form-engine-lib
```

Then create a form with only one page to test your changes.

**Comment by jona42-ui** [comment]
nav2

**Comment by jona42-ui** [comment]
Screenshot from 2023-06-30 16-38-33

**Comment by ebambo** [comment]
@jona42-ui can you please add a screenshot or video of this working using the `React Form Engine`. The example shared uses the `Angular Form Engine`?

**Comment by samuelmale** [comment]
@jona42-ui are you still working this?

**Comment by jona42-ui** [comment]
@samuelmale  
trying to test out the changes but continuously get this error on linking,any workaround
image

**Comment by pirupius** [comment]
Hi @jona42-ui i know it was been long since this work was attended to. The issue with linking was resolved a while back and if you have some time please test this again and share relevant screenshots/video recording so we can get this merged in.

**Comment by jona42-ui** [comment]
okay thanks

**Comment by jona42-ui** [comment]
solved  here: https://github.com/openmrs/openmrs-form-engine-lib/pull/180

closing this as complete.

**Pull request closed without merging**
