### PR TITLE
O3-3161 Capture obs comments

### PR DESCRIPTION
**Pull request by CynthiaKamau**
## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary

- Capture obs comments if user adds `showComments` true

## Screenshots

https://www.loom.com/share/afe8ff2306b8478fb17f30514381bb3f?sid=3bb53ebd-8336-4f5a-b573-5a4fdded013e

### CODE REVIEW

**Comment by samuelmale** [comment]
@ibacher should we instead use a text area for capturing obs comments?

**Comment by ibacher** [comment]
No. The field only allows 255 characters. It's intended for short notes. If you need something longer, I'd suggest creating an ObsGroup with one obs being the value and a second obs as the comment, since Obs with text values can store arbitrary-length notes.

**Review by hadijahkyampeire — APPROVED** [review]
This looks good, thanks @CynthiaKamau

**Review by arodidev — APPROVED** [review]
Thanks @CynthiaKamau LGTM

**Pull request merged**
