### PR TITLE
(feat) O3-3029: support for historical expressions

### PR DESCRIPTION
**Pull request by arodidev**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary

This PR introduces support for historical expressions to the form's engine by leveraging the existing  `previous-value` functionality, making the previous value available when either `formField.historicalExpression` or `formField.questionOptions.enablePreviousValue` resolve to `true`. 

This is enabled by refactoring the `questionOptions` property `usePreviousValueDisabled` to `enablePreviousValue` to allow for lexical accuracy when using their resolved boolean values to enable and disable the `previous-value` functionality. 

By default, the previous encounter will always be available in the form unless explicitly specified otherwise. ie `formOptions.usePreviousValueDisabled == true` and using this would make the historical expression functionality seize to work.

### CODE REVIEW

**Comment by samuelmale** [comment]
@arodidev Are you planning on setting up the [HD](https://github.com/openmrs/openmrs-ngx-formentry/blob/9dbbf324fcc6ec6fa49fe4f954801f173a00c764/projects/ngx-formentry/src/form-entry/helpers/historical-expression-helper-service.ts) object in the expression runner's context to make it possible to resolve expressions like: `"historicalExpression": "HD.getObject('prevEnc').getValue('a8a6619c-1350-11df-a1f1-0026b9348838')"` out of the box?

Something like:

```ts
class HistoricalService {
  dataSourceMap: Record<string, any> = {};

  putObject(key: string, value: any) {
    this.dataSourceMap[key] = value;
  }

  getObject(key: string) {
    return this.dataSourceMap[key];
  }
}

// Instantiate one
export const HD = new HistoricalService();
// Setup previous encounter
HD.putObject('prevEnc', {
  value: encounterContex.previousEncounter,
  getValue(concept) {
    // lookup obs
    return this.value.obs.find((obs) => obs.concept.uuid == concept)?.value;
  },
});

// We then add the instance of `HistoricalService` to the context of the expression runner.

```

**Comment by arodidev** [comment]
> @arodidev Are you planning on setting up the [HD](https://github.com/openmrs/openmrs-ngx-formentry/blob/9dbbf324fcc6ec6fa49fe4f954801f173a00c764/projects/ngx-formentry/src/form-entry/helpers/historical-expression-helper-service.ts) object in the expression runner's context to make it possible to resolve expressions like: `"historicalExpression": "HD.getObject('prevEnc').getValue('a8a6619c-1350-11df-a1f1-0026b9348838')"` out of the box?
> 
> Something like:
> 
> ```ts
> class HistoricalDataSourceService {
>   dataSourceMap: Record<string, any> = {};
> 
>   putObject(key: string, value: any) {
>     this.dataSourceMap[key] = value;
>   }
> 
>   getObject(key: string) {
>     return this.dataSourceMap[key];
>   }
> }
> 
> // Instantiate one
> export const HD = new HistoricalDataSourceService();
> // Setup previous encounter
> HD.putObject('prevEnc', {
>   value: encounterContex.previousEncounter,
>   getValue(concept) {
>     // lookup obs
>     return this.value.obs.find((obs) => obs.concept.uuid == concept)?.value;
>   },
> });
> 
> // We then add the instance of `HistoricalDataSourceService ` to the context of the expression runner.
> ```

Not really, I believe we already support functionality for retrieving the field's previous value by concept UUID from the previous encounter, my implementation is just a reuse of the existing logic but with minor tweaks. Was the idea to implement the functionality you've mentioned above?

**Comment by samuelmale** [comment]
@arodidev Well to the most part that may work, except for a few edge cases. If you checkout [this Ampath form](https://github.com/AMPATH/openmrs-config-amrs/blob/6ac130fea89d1e7e826ac4b387e65cd99c0afe82/configuration/ampathforms/ampath%20poc%20medication%20refill%20encounter%20form%20v1.3.json#L464). It seems to paint a more complicated scenario:
```json
{
  "label": "Line of ART patient is taking:",
  "id": "current_arv_line",
  "historicalExpression": "!_.isEmpty(HD.getObject('prevEnc').getValue('a89b6a62-1350-11df-a1f1-0026b9348838')) ? undefined : HD.getObject('prevEnc').getValue('04616f5d-b961-4f41-bbd7-bcc0dd235577')",
  "questionOptions": {
    "concept": "04616f5d-b961-4f41-bbd7-bcc0dd235577",
    "answers": [
      {
        "concept": "034047bd-3fa1-4b2a-b0f0-2787e9b9f7b3",
        "label": "First line regimen"
      },
      {
        "concept": "8f8a715d-e49a-4b2c-aa3a-83fa9d7a4254",
        "label": "Second line regimen"
      },
      {
        "concept": "a90ebdd2-351f-485a-b850-4938fcca2729",
        "label": "Third line regimen"
      }
    ],
    "rendering": "select"
  },
  "type": "obs",
  "validators": [
    {
      "type": "js_expression",
      "failsWhenExpression": "isEmpty(myValue) && !isEmpty(onArt) && onArt === 'a899b35c-1350-11df-a1f1-0026b9348838'",
      "message": "Patient previously marked as on ART. Please provide the treatment category."
    }
  ],
  "hide": {
    "hideWhenExpression": "onArt !== 'a899b35c-1350-11df-a1f1-0026b9348838'||  arrayContains (['6bf34991-7414-4b5e-ad75-ca217d4c4939'],visitTypeUuid)"
  }
}

```

Would the existing logic meet the semantics of the "historicalExpression" above?

**Comment by arodidev** [comment]
@samuelmale I see, back to the drawing board it is...

**Pull request closed without merging**
