### PR TITLE
feat: should reset field values on hide

### PR DESCRIPTION
**Pull request by usamaidrsk**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

### CODE REVIEW

**Comment by samuelmale** [comment]
@usamaidrsk are you still working on this?

**Comment by usamaidrsk** [comment]
> @usamaidrsk are you still working on this?

Yes @samuelmale, will update the PR and make it ready for review.

**Comment by brandones** [comment]
Hi @usamaidrsk , what's the status?

**Comment by usamaidrsk** [comment]
Hi @samuelmale,
Following the discussion we had and the feedback provided, I'm closing this PR. I did add a comment on the [ticket](https://openmrs.atlassian.net/browse/O3-3388?focusedCommentId=142371).
Thanks

**Comment by usamaidrsk** [comment]
Hi @samuelmale,
Following the discussion we had and the feedback provided, I'm closing this PR. I did add a comment on the [ticket](https://openmrs.atlassian.net/browse/O3-3388?focusedCommentId=142371).
Thanks

**Pull request closed without merging**
