### PR TITLE
(feat)O3-2210: Add support for file picker to form engine

### PR DESCRIPTION
**Pull request by jona42-ui**
## Requirements

- [X] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [X] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [X] My work includes tests or is validated by existing tests.

## Summary

Added  a file component and schema update to include the required questionOption for rendering files, including specifications such as maximum allowed file size and allowed file types (e.g., .jpg). like 
   1. Single File Attachments
   2. Multiple file attachments
Implented a preview feature for files that are yet to be uploaded.

## Screenshots

Screencast from 13-08-23 22 26 51

## Related Issue

[O3-2210](https://issues.openmrs.org/browse/O3-2210)

### CODE REVIEW

**Comment by jona42-ui** [comment]
cc @samuelmale @eudson @donaldkibet

**Comment by jona42-ui** [comment]
[Screencast from 21-08-23 11:59:03.webm](https://github.com/openmrs/openmrs-form-engine-lib/assets/78595738/c62628a5-6bf2-4080-afa0-79dc889ac70c)

**Comment by jona42-ui** [comment]
Hello
It seems the form data is not persisted to the server.
On form submission, all seems well on the network tab yet actually no encounter is created.
1. do we have an  API endpoint  that accepts file uploads in the forms?

**Comment by samuelmale** [comment]
@jona42-ui did you intend to pickup where @donaldkibet left with https://github.com/openmrs/openmrs-form-engine-lib/pull/88?

**Comment by jona42-ui** [comment]
> @jona42-ui did you intend to pickup where @donaldkibet left with #88?

sure @samuelmale though I needed more of either  an editor that opens image files in new tab or  a pop up window on annotation then persisting the clinical  images on encounter

**Comment by ibacher** [comment]
> does the WS/REST module support Complex Obs out of the box?

It should. REST is generally a pretty thin wrapper around the underlying Java APIs and we certainly support complex obs there. However, correctly creating complex obs is, well, complex. They rely on having an appropriate set of handlers on the backend to work with the data (complex obs are basically stored as a binary string that's interpreted by a handler).

**Comment by jona42-ui** [comment]
> 

Thanks @ibacher 
Are there any specific considerations for incorporating Complex Obs within the context of form handlers and submission processes?

I was thinking  to have a utility somewhat like this;

````
export async function handleFileUpload(fileData, fieldName) {
  try {
    // Adapt the API endpoint for file upload
    const url = '/ws/rest/v1/upload'; // Adjusting  the endpoint as needed

```
    // Create FormData and append the file data
    const formData = new FormData();
    formData.append('file', fileData);

    // Use openmrsFetch to upload the file
    const response = await openmrsFetch(url, {
      method: 'POST',
      body: formData,
    });`

**Comment by jona42-ui** [comment]
> However, correctly creating complex obs is, well, complex.

abit scared @ibacher but atleast i wanted to persist the images to complete my gsoc project, what advice can you give to me kindly  to have something functional. thanks so much.

**Comment by jona42-ui** [comment]
> > does the WS/REST module support Complex Obs out of the box?
> 
> It should. REST is generally a pretty thin wrapper around the underlying Java APIs and we certainly support complex obs there. However, correctly creating complex obs is, well, complex. They rely on having an appropriate set of handlers on the backend to work with the data (complex obs are basically stored as a binary string that's interpreted by a handler).

@ibacher I had a temporary hack and used the attachment resources to persist the image though this is not the plan for the forms'  data to save the images//complex obs.
Are there any initial thoughts/plans to get this implementation kick started?

**Comment by ibacher** [comment]
@jona42-ui Ultimately, I think using the attachment resource is the right idea here. The trick is to ensure it's attached to the same encounter as the form.

**Comment by samuelmale** [comment]
Closing this because work is being track at https://github.com/openmrs/openmrs-form-engine-lib/pull/128

**Pull request closed without merging**
