### PR TITLE
(feat) Add generic fetch with error handling

### PR DESCRIPTION
**Pull request by donaldkibet**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary
This Pull Request introduces a generic fetch function and a custom error class for handling fetch failures.

The fetch function simplifies making HTTP requests in the form engine by automatically handling JSON stringification, ensuring appropriate header inclusion, and providing detailed error feedback in the case of request failures. This function will throw an error when provided with invalid arguments, and it automatically stringifies JavaScript objects sent in the request body (except for FormData instances).

Alongside this, we introduce a GenericFetchError class, extending the JavaScript Error class, to give detailed information about failed fetch requests. When a request fails, a GenericFetchError will be thrown, providing the URL of the request, the received server response, any available response body, and the stack trace before the request was made.

## Screenshots
Peek 2023-05-23 18-31

## Example

```json
{
  "name": "Fetch Test form",
  "pages": [
    {
      "label": "Page 1",
      "sections": [
        {
          "label": "Section 1",
          "isExpanded": "true",
          "questions": [
            {
              "label": "Body Weight",
              "type": "obs",
              "questionOptions": {
                "rendering": "textarea",
                "concept": "560555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                "calculate": {
                  "calculateExpression": "resolve(api.genericFetch('https://api.chucknorris.io/jokes/random'))?.data?.value"
                },
                "conceptMappings": [
                  {
                    "type": "CIEL",
                    "value": "160555"
                  }
                ]
              },
              "id": "bodyWeight",
              "validators": [],
              "required": "true",
              "unspecified": "true"
            },
            {
              "label": "Calculated field",
              "type": "obs",
              "questionOptions": {
                "rendering": "textarea",
                "concept": "560555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                "calculate": {
                  "calculateExpression": "resolve(api.genericFetch('https://api.chucknorris.io/jokes/random'))?.data?.value"
                },
                "conceptMappings": [
                  {
                    "type": "CIEL",
                    "value": "160555"
                  }
                ]
              },
              "id": "dyM",
              "validators": [],
              "required": "true"
            }
          ]
        }
      ]
    }
  ],
  "availableIntents": [],
  "processor": "EncounterFormProcessor",
  "uuid": "na24c540-cc83-43bc-978f-c1ef180a597f",
  "referencedForms": [],
  "encounterType": "d1059fb9-a079-4feb-a749-eedd709ae542",
  "version": "1.0",
  "description": "Tra=iage"
}
```

### CODE REVIEW

**Comment by ibacher** [comment]
I'm not really sure I understand why we need this instead of just using `openmrsFetch()`? I'd prefer to keep just one fetch wrapper in the ecosystem unless there's some really specialised need I'm not seeing here.

**Comment by samuelmale** [comment]
@ibacher I don't want to deflect from your argument but does `openmrsFetch()` support external APIs? I imagine there could be a use case for fetching data from arbitrary APIs.

**Comment by ibacher** [comment]
@samuelmale It's intended to, though we may need to adjust `makeUrl()` by the looks of things.

**Comment by mogoodrich** [comment]
I'm not enough into the details of O3 to make detailed comments yet, but I agree if we can stick with a single fetch wrapper in the ecosystem, but certainly interested in @donaldkibet 's thoughts on why we may need another one.

**Comment by samuelmale** [comment]
Just to put this at bed, @ibacher @donaldkibet all we need to do is add `openmrsFetch()`?

**Pull request closed without merging**
