### PR TITLE
(fix) O3-3111: Fix stylings in the side navigation

### PR DESCRIPTION
**Pull request by WodPachua**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary
When you try to submit a form with validation errors, the affected pages are highlighted for visibility. Previously the styling was  broken, this fix addresses that issue.

## Screenshots
styling fix
Screenshot from 2024-04-24 19-56-11

## Related Issue
https://openmrs.atlassian.net/browse/O3-3111

### CODE REVIEW

**Comment by pirupius** [comment]
Aponyo @WodPachua please add a gif or video recording to the description

**Comment by WodPachua** [comment]
@pirupius I am getting a blocker after resolving the conflicting file, It seems I can't open and view any forms now... not sure why...

**Comment by pirupius** [comment]
@WodPachua which frontend are u using to test? 
Some breaking changes were merged and you might need to
- Pull the latest changes for the form builder or form engine app
- Install updates 
- You might need to re-link the form engine

**Comment by WodPachua** [comment]
I have tried doing that, pulled changes, relinked the form engine, however, the spa is not fully loading. @pirupius

**Comment by samuelmale** [comment]
@WodPachua the dev server was down but @denniskigen just restarted it.

**Review by denniskigen — APPROVED** [review]
LGTM

**Comment by WodPachua** [comment]
Thanks @samuelmale @pirupius @denniskigen . I have added a gif.

**Review by pirupius — APPROVED** [review]
Thanks @WodPachua

**Comment by WodPachua** [comment]
Thanks @pirupius Though, am noticing another bug, the highlighting is only seen when you try to save before  scrolling, however if you first scroll, then try to save, this action isn't seen.

**Comment by pirupius** [comment]
@WodPachua would be grateful of you can submit a PR for it with `(fix)` in the title and explain the behaviour in the description. (Don't forget to add a video/gif) of the before and after

**Pull request merged**
