### PR TITLE
(faet)O3-2322: Triggering  the drawing widget by  path to the image.

### PR DESCRIPTION
**Pull request by jona42-ui**
## Requirements

- [X] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [X] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [X] My work includes tests or is validated by existing tests.

## Summary

Following the file [picker](https://github.com/openmrs/openmrs-form-engine-lib/pull/103) implementation, in this PR addresses the sharing of state between the file picker and the drawing widget.
With an embedded diagram in the form, it has a button that when clicked, it should pass the image url/path  to the drawing tool for annotation.

Basically the workflow is meant to be;
Pick an image file  within form -> File has an annotate button
Click annotate -> path to the image passed to drawing widget
Save annotated image(in drawing tool) -> original image path updated and sent back to the form
Updated image url part of form submission.

In this PR, i created;
1. OHRIAnnotate component that encapsulates the annotation functionality
2. config context to specify url of the drawing widget
3. usePatient hook from openmrsframework  to access the patient UUID from the URL

## Screenshots

Screenshot from 2023-08-15 16-27-23

[Screencast from 15-08-23 17:29:05.webm](https://github.com/openmrs/openmrs-form-engine-lib/assets/78595738/287110c7-ab11-4754-b789-0e74c90c9c93)

## Related Issue

[O3-2322](https://issues.openmrs.org/browse/O3-2322)

### CODE REVIEW

**Comment by jona42-ui** [comment]
@samuelmale can we get a util function from the patient commons lib to get the trigger implemented

**Comment by jona42-ui** [comment]
[persist images.webm](https://github.com/openmrs/openmrs-form-engine-lib/assets/78595738/fdf4d7d4-c6ff-4aa7-8df6-110b5204c559)

**Comment by samuelmale** [comment]
@jona42-ui are you still working this?

**Comment by jona42-ui** [comment]
@samuelmale nope,  its oaky to close this

**Pull request closed without merging**
