### PR TITLE
fix(O3-2491): Improved Time Rendering Logic Implementation

### PR DESCRIPTION
**Pull request by senthil-k8s**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [x] My work includes tests or is validated by existing tests.

## Summary
Currently the form engine supports `date` and `datetime` rendering only. 

Within the `inbuiltControls.ts` all the controls are listed and  added  `time` seperately

Both `date` and `datetime` rendering use `OHRIDate` ([Component Link](https://github.com/openmrs/openmrs-form-engine-lib/blob/feat/support-reusable-components/src/components/inputs/date/ohri-date.component.tsx)). So, I decided to add the `time` logic inside of the component.

## Screenshots
https://www.loom.com/share/ac4128e2ea9745798baea042de665866?sid=ba1308d5-2b6f-40d5-bec1-6c3d6866bc6e

## Related Issue
https://openmrs.atlassian.net/browse/O3-2491

## Other
While Fetching, we have to ensure that time is also separate. questionTypes.

### CODE REVIEW

**Comment by senthil-k8s** [comment]
Hey @denniskigen, changes are made based on request, time component is rendered on it's own, irrespective of the date component.
Link: https://openmrs.atlassian.net/browse/O3-2491?focusedCommentId=139201

**Comment by samuelmale** [comment]
@senthil-k8s did you see the build failure? Do you still have the bandwidth to push this?

**Comment by senthil-k8s** [comment]
I haven't seen this; I'll look into it. Thanks @samuelmale for noticing

**Comment by samuelmale** [comment]
@senthil-k8s please note that we need to proactively gear this work up because most of the form-engine tasks under [this epic](https://openmrs.atlassian.net/browse/O3-2193)  are candidates of the upcoming hackathon and the goal is to have these low hanging fruits out of the way prior to the hackathon. Same case applies other tasks like [this](https://github.com/openmrs/openmrs-form-engine-lib/pull/177). If you think you don't have enough suspense or not sure on how to address the issues, kindly feel free to pickup some other work to create room for the dedicated workforce.

Thanks for your amazing contributions!

**Comment by senthil-k8s** [comment]
@samuelmale, build error resolved, as well as in other [cases](https://github.com/openmrs/openmrs-form-engine-lib/pull/177). Logic is written in the same date component, which ensures that time and date components rendered separately. As well, the logic works for both rendering the datetime simultaneously. else time needs to be in a separate component?

**Comment by samuelmale** [comment]
From the attached GIF, this seems to capture `datetime` and not strictly `time`

**Comment by senthil-k8s** [comment]
here is the updated one: https://www.loom.com/share/c8f412d4151a4c2a857d93dd0ef13a92?sid=8c4c3bd8-a4f5-414f-aee0-c6019891461d

**Comment by samuelmale** [comment]
Cancelling this because of the lack of a real world usecase

**Pull request closed without merging**
